/** Shared Instagram-grade chat UI tokens (group + direct messages). */
export const chatPremium = {
  wallpaper: "chat-premium-wallpaper min-h-0 flex-1 overflow-x-hidden overflow-y-auto py-3",
  datePill: "chat-premium-date-pill",
  panel:
    "chat-premium-panel fixed inset-0 z-50 flex min-w-0 max-w-full flex-col overflow-x-hidden font-sans lg:relative lg:inset-auto lg:z-auto lg:min-h-[min(720px,calc(100dvh-10rem))] lg:overflow-hidden lg:rounded-[1.75rem] lg:shadow-[0_24px_80px_rgba(45,36,24,0.12)] dark:lg:shadow-[0_24px_80px_rgba(0,0,0,0.45)]",
  groupHeader:
    "chat-premium-group-header shrink-0 px-3 pb-3 pt-[max(0.5rem,env(safe-area-inset-top))]",
  headerIconButton: "chat-premium-header-icon-btn",
  headerTitle: "truncate font-display text-[15px] font-semibold tracking-tight text-night-950 dark:text-sand-50",
  headerSubtitle:
    "truncate text-[11px] font-medium tracking-wide text-night-500 underline decoration-night-400/40 decoration-dotted underline-offset-[3px] dark:text-sand-400",
  headerAvatarRing: "chat-premium-header-avatar-ring",
  composerBar:
    "chat-premium-composer-bar shrink-0 px-3 py-2 pb-[max(0.35rem,env(safe-area-inset-bottom))]",
  composerRow: "flex min-w-0 w-full items-end gap-2",
  composerField: "chat-premium-composer-field",
  composerInput:
    "w-full bg-transparent text-[15px] leading-snug text-night-900 outline-none placeholder:text-night-400 disabled:opacity-50 dark:text-sand-100 dark:placeholder:text-sand-500",
  sendButton: "chat-premium-send-btn",
  composerIconButton: "chat-premium-composer-icon-btn",
  emojiTray: "chat-premium-emoji-tray",
  emojiTrayBtn: "chat-premium-emoji-tray-btn",
  attachmentPreview: "chat-premium-attachment-preview",
  contextMenu: "chat-premium-context-menu",
  contextMenuItem: "chat-premium-context-menu-item",
  contextMenuItemDanger: "chat-premium-context-menu-item chat-premium-context-menu-item-danger",
  reactionPicker: "chat-premium-reaction-picker",
  reactionCategoryActive: "chat-premium-reaction-tab chat-premium-reaction-tab-active",
  reactionCategoryIdle: "chat-premium-reaction-tab",
  reactionEmojiBtn: "chat-premium-reaction-emoji-btn",
  reactionPill: "chat-premium-reaction-pill",
  reactionPillActive: "chat-premium-reaction-pill chat-premium-reaction-pill-active",
  replyBanner: "chat-premium-reply-banner",
  replyQuoteOut: "chat-premium-reply-quote chat-premium-reply-quote-out",
  replyQuoteIn: "chat-premium-reply-quote chat-premium-reply-quote-in",
  selectionChip: "chat-premium-selection-chip",
  senderLabel: "chat-premium-sender-label",
  bubbleOut: "chat-premium-bubble chat-premium-bubble-out",
  bubbleIn: "chat-premium-bubble chat-premium-bubble-in",
  bubbleMeta: "chat-premium-bubble-meta",
  attachmentImage: "chat-premium-attachment-image",
  emptyCard: "chat-premium-empty-card",
  statusBanner: "chat-premium-status-banner",
  overflowMenu: "chat-premium-overflow-menu",
  overflowMenuItem: "chat-premium-overflow-menu-item",
  sheetBackdrop: "chat-premium-sheet-backdrop",
  sheetPanel: "chat-premium-sheet-panel",
  sheetHeader: "chat-premium-sheet-header",
  sheetSearch: "chat-premium-sheet-search",
  sheetRow: "chat-premium-sheet-row",
  participantAvatar: "chat-premium-participant-avatar",
  sheetMessageBtn: "chat-premium-sheet-message-btn",
  deletedNotice: "chat-premium-deleted-notice",
} as const;
